name: quick_search
description: A package allow you to create a search repository for quick search.
version: 0.1.0
homepage: https://github.com/ddao33/quick_search

environment:
  sdk: ^3.5.2

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
